name : python_test
on:
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  python_test_job:
    name: python_test_job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        id: check_something
        shell: bash
        run: |
          echo $(pwd)
          docker image build -t my_github_practice .
          docker container run --name my_github_practice_container -v $(pwd)/tests/results:/app/tests/results -t my_github_practice
          docker exec my_github_practice_container pytest -v --junitxml="/app/tests/results/python_test_job.xml"
        continue-on-error: true

      # テスト結果の表示
      - name: Upload Unit Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results
          path: /app/tests/results/*.xml

      - name: Download Artifacts
        if: success() || failure()
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/*xml

      - name : something when command success
        if: steps.check_something.outcome == 'success' #  - name: testの箇所が成功したか失敗したかで処理を変える
        shell: bash
        run: echo "test success!!!"

      - name: something when command failure
        if: steps.check_something.outcome == 'failure' #  - name: testの箇所が成功したか失敗したかで処理を変える
        shell: bash
        run: exit 1